"""Rank declaration pairs by the preregistered Sprint 1 score.

Primary score: the mean of the min-max normalized name-free Weisfeiler–Lehman
cosine and the normal-form score. The normal-form score is 1 when the curated
forms hash equal, and 0 otherwise. Exact digest and the keep-names kernel are
reported and are not part of the primary rank. The semantic arm is not run.
"""

from __future__ import annotations

import hashlib
import json
import math
from collections import Counter
from pathlib import Path

from consilean.distance.hub import distances_at
from consilean.ingest.corpus import CorpusSpec
from consilean.ingest.declarations import Declaration, load_declarations
from consilean.ingest.graph import undirected_distances
from consilean.vendor.import_graph import build
from consilean.views.syntax import formula_graph, normal_form, parse_statement
from consilean.views.wl import cosine, wl_features

GENERATING_COMMAND = "uv run consilean-sprint1"
TWIN = {"isSquare_neg_one_mod_markovNumber", "exists_sq_modEq_neg_one_markovNumber"}
HUB_FRACTIONS = (0.0, 0.01, 0.05)


def build_report(root: Path, spec: CorpusSpec) -> dict:
    declarations = [decl for decl in load_declarations(root) if decl.kind in {"theorem", "lemma"}]
    graph = build(root, spec.namespace)
    base_distances = undirected_distances(graph)
    rows = [_view(decl) for decl in declarations]
    pairs = _pairs(declarations, rows, base_distances)
    twin = _find_twin(pairs)
    return {
        "generating_command": GENERATING_COMMAND,
        "corpus": {
            "repo": spec.repo,
            "revision": spec.revision,
            "namespace": spec.namespace,
            "lean": spec.lean,
            "mathlib": spec.mathlib,
        },
        "primary": "mean of min-max normalized name-free WL cosine and normal-form equality",
        "ranked_kinds": ["theorem", "lemma"],
        "parsed": sum(1 for row in rows if row["parsed"]),
        "declarations": len(rows),
        "cross_module_pairs": len(pairs),
        "twin": twin,
        "top": pairs[:10],
        "top_distance_at_least_4": [pair for pair in pairs if _far(pair, 4)][:10],
        "top_no_import_path": [pair for pair in pairs if pair["distance"] is None][:10],
        "hubs": _hubs(graph, declarations),
        "semantic": {
            "status": "not_run",
            "reason": (
                "Sprint 1 spends no tokens. The local embedding model was not fetched, "
                "and MELD was not scored. This arm is not part of the primary rank."
            ),
        },
        "probes": {
            "status": "not_run",
            "reason": (
                "Tactic probes need a LeanFrontier environment. Running them in the "
                "sibling checkout would write build files into another project. "
                "The notation equivalence of the twin is the Lean file "
                "lean/IsSquareModEq.lean, checked separately when a Mathlib v4.34.0 "
                "cache is available."
            ),
        },
    }


def write_generated(repo: Path, report: dict) -> tuple[Path, Path]:
    out = repo / "docs" / "generated"
    out.mkdir(parents=True, exist_ok=True)
    json_path = out / "sprint1-leanfrontier-79800a5.json"
    md_path = out / "sprint1-leanfrontier-79800a5.md"
    json_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    md_path.write_text(render_markdown(report), encoding="utf-8")
    return json_path, md_path


def render_markdown(report: dict) -> str:
    twin = report["twin"]
    lines = [
        "# Sprint 1 views",
        "",
        f"Generated by `{report['generating_command']}`.",
        f"Revision: `{report['corpus']['revision']}`.",
        "",
        "Do not edit this file by hand. Re-run the command.",
        "",
        f"- ranked: {', '.join(report['ranked_kinds'])}",
        f"- declarations: {report['declarations']}",
        f"- parsed: {report['parsed']}",
        f"- cross-module pairs: {report['cross_module_pairs']}",
        f"- primary: {report['primary']}",
        "",
        "## Twin",
        "",
        _twin_line(twin),
        f"- exact digests equal: {twin['exact_digests_equal'] if twin else None}",
        f"- normal forms equal: {twin['normal_forms_equal'] if twin else None}",
        f"- name-free WL cosine: {_num(twin['wl_name_free'] if twin else None)}",
        f"- keep-names WL cosine: {_num(twin['wl_keep_names'] if twin else None)}",
        "",
        "## Top pairs by the primary score",
        "",
        _table(report["top"]),
        "",
        "## Top pairs at import distance at least 4",
        "",
        _table(report["top_distance_at_least_4"]),
        "",
        "## Top pairs with no import path",
        "",
        _table(report["top_no_import_path"]),
        "",
        "## Hub removal",
        "",
        _hub_table(report["hubs"]),
        "",
        "## Not run",
        "",
        f"- semantic: {report['semantic']['reason']}",
        f"- tactic probes: {report['probes']['reason']}",
        "",
    ]
    return "\n".join(lines)


def print_report(report: dict) -> None:
    twin = report["twin"]
    if twin is None:
        print("sqrt(-1) twin: not ranked")
        return
    print(
        f"sqrt(-1) twin primary rank {twin['rank']} of {twin['of']}, "
        f"score {twin['primary']:.4f}, normal forms equal: {twin['normal_forms_equal']}"
    )
    print(f"parsed {report['parsed']} of {report['declarations']} declarations")


def _view(decl: Declaration) -> dict:
    statement = parse_statement(decl.raw_sig)
    text = " ".join(decl.raw_sig.split())
    if statement is None:
        features = Counter({f"unparsed:{hashlib.sha256(text.encode()).hexdigest()}": 1})
        return {
            "parsed": False,
            "normal": None,
            "digest": hashlib.sha256(text.encode()).hexdigest(),
            "name_free": features,
            "keep_names": features,
        }
    return {
        "parsed": True,
        "normal": normal_form(decl.raw_sig),
        "digest": hashlib.sha256(text.encode()).hexdigest(),
        "name_free": wl_features(*formula_graph(statement, keep_names=False)),
        "keep_names": wl_features(*formula_graph(statement, keep_names=True)),
    }


def _pairs(decls: list[Declaration], rows: list[dict], distances: dict[str, dict[str, int]]) -> list[dict]:
    raw: list[tuple[float, float, int, int]] = []
    wl_values: list[float] = []
    nf_values: list[float] = []
    for i in range(len(decls)):
        for j in range(i + 1, len(decls)):
            if decls[i].module == decls[j].module:
                continue
            wl_values.append(cosine(rows[i]["name_free"], rows[j]["name_free"]))
            left_nf = rows[i]["normal"]
            right_nf = rows[j]["normal"]
            nf_values.append(1.0 if left_nf is not None and left_nf == right_nf else 0.0)
            raw.append((0.0, 0.0, i, j))
    wl_norm = _minmax(wl_values)
    nf_norm = _minmax(nf_values)
    scored: list[dict] = []
    for index, (_, _, i, j) in enumerate(raw):
        primary = (wl_norm[index] + nf_norm[index]) / 2
        distance = distances.get(decls[i].module, {}).get(decls[j].module, math.inf)
        scored.append(
            {
                "primary": primary,
                "wl_name_free": wl_values[index],
                "wl_name_free_norm": wl_norm[index],
                "normal_form": nf_values[index],
                "normal_form_norm": nf_norm[index],
                "distance": None if math.isinf(distance) else distance,
                "left": f"{decls[i].module}.{decls[i].name}",
                "right": f"{decls[j].module}.{decls[j].name}",
                "exact_digests_equal": rows[i]["digest"] == rows[j]["digest"],
                "normal_forms_equal": nf_values[index] == 1.0,
                "wl_keep_names": cosine(rows[i]["keep_names"], rows[j]["keep_names"]),
            }
        )
    scored.sort(key=lambda row: (-row["primary"], -row["normal_form"], row["left"], row["right"]))
    return scored


def _find_twin(pairs: list[dict]) -> dict | None:
    for index, pair in enumerate(pairs, start=1):
        names = {pair["left"].rsplit(".", 1)[-1], pair["right"].rsplit(".", 1)[-1]}
        if names == TWIN:
            found = dict(pair)
            found["rank"] = index
            found["of"] = len(pairs)
            return found
    return None


def _hubs(graph: dict[str, list[str]], decls: list[Declaration]) -> list[dict]:
    modules = {decl.name: decl.module for decl in decls if decl.name in TWIN}
    if len(modules) != 2:
        return []
    left_mod, right_mod = modules["isSquare_neg_one_mod_markovNumber"], modules["exists_sq_modEq_neg_one_markovNumber"]
    rows = []
    for fraction in HUB_FRACTIONS:
        distances, hubs = distances_at(graph, fraction)
        distance = distances.get(left_mod, {}).get(right_mod, math.inf)
        rows.append(
            {
                "fraction": fraction,
                "hubs_removed": hubs,
                "twin_distance": None if math.isinf(distance) else distance,
                "modules_remaining": len(distances),
            }
        )
    return rows


def _minmax(values: list[float]) -> list[float]:
    if not values:
        return []
    lo = min(values)
    hi = max(values)
    if hi == lo:
        return [0.0 for _ in values]
    return [(value - lo) / (hi - lo) for value in values]


def _far(pair: dict, cutoff: int) -> bool:
    distance = pair["distance"]
    return distance is not None and distance >= cutoff


def _twin_line(twin: dict | None) -> str:
    if twin is None:
        return "- sqrt(-1) twin: not ranked"
    return (
        f"- sqrt(-1) twin: primary {twin['primary']:.4f}, "
        f"rank {twin['rank']} of {twin['of']}, distance {_dist(twin['distance'])}"
    )


def _num(value: float | None) -> str:
    return "none" if value is None else f"{value:.4f}"


def _dist(distance: int | None) -> str:
    return "∞" if distance is None else str(distance)


def _short(name: str) -> str:
    return name.removeprefix("LeanFrontier.")


def _table(rows: list[dict]) -> str:
    header = "| primary | normal form | WL | distance | left | right |"
    rule = "|---:|---:|---:|---:|---|---|"
    body = [
        "| {primary:.4f} | {nf:.0f} | {wl:.4f} | {dist} | `{left}` | `{right}` |".format(
            primary=row["primary"],
            nf=row["normal_form"],
            wl=row["wl_name_free"],
            dist=_dist(row["distance"]),
            left=_short(row["left"]),
            right=_short(row["right"]),
        )
        for row in rows
    ]
    return "\n".join([header, rule, *body]) if body else "(none)"


def _hub_table(rows: list[dict]) -> str:
    header = "| fraction | hubs removed | modules left | twin distance |"
    rule = "|---:|---:|---:|---:|"
    body = [
        f"| {row['fraction']:.0%} | {len(row['hubs_removed'])} | {row['modules_remaining']} | {_dist(row['twin_distance'])} |"
        for row in rows
    ]
    return "\n".join([header, rule, *body]) if body else "(none)"
