"""Freeze the Mathlib duplicate set, then measure H2 recall. No tokens."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from consilean.ingest.declarations import load_declarations
from consilean.replay.ground_truth import collect_ground_truth
from consilean.replay.recall import recall_at_k

GENERATING_COMMAND = "uv run consilean-sprint2"
MATHLIB_REV = "5ed2965256430c3649e86755f9576b54eca72435"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    from consilean.ingest.corpus import repo_root

    root = repo_root()
    mathlib = _mathlib_root(root)
    if mathlib is None:
        raise SystemExit("local Mathlib v4.34.0 tree not found")
    frozen = collect_ground_truth(mathlib)
    frozen["corpus"] = "Mathlib"
    frozen["revision"] = MATHLIB_REV
    frozen["generating_command"] = GENERATING_COMMAND
    out = root / "docs" / "generated"
    out.mkdir(parents=True, exist_ok=True)
    freeze_path = out / "sprint2-ground-truth.json"
    # Score only the pairs just frozen. The hash is stored with them.
    declarations = load_declarations(mathlib, namespace="Mathlib")
    measured = recall_at_k(declarations, frozen["pairs"])
    report = {
        "generating_command": GENERATING_COMMAND,
        "revision": MATHLIB_REV,
        "ground_truth_sha256": frozen["sha256"],
        "ground_truth_count": frozen["count"],
        "h2": measured,
        "h3": {
            "status": "not_measured",
            "reason": (
                "H3 needs a ranking of the corpus at past Mathlib releases. "
                "This run does not check out those revisions. "
                "The since dates are stored on the frozen pairs."
            ),
        },
        "duplicate_list": {
            "rows": [],
            "reason": "No equivalence was closed by the checker in this run, so the published list is empty.",
        },
    }
    freeze_path.write_text(json.dumps(frozen, indent=2) + "\n", encoding="utf-8")
    (out / "sprint2-h2.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    (out / "sprint2-h2.md").write_text(_markdown(report, frozen), encoding="utf-8")
    (out / "sprint2-duplicates.md").write_text(
        "\n".join(
            [
                "# Probable duplicates",
                "",
                f"Generated by `{GENERATING_COMMAND}`.",
                "",
                "No row is listed. The checker did not close an equivalence in this run.",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(f"frozen {frozen['count']} sha256 {frozen['sha256'][:12]}")
    print(f"recall@10 {measured['recall'].get('10')}")
    print(f"wrote {freeze_path}")


def _mathlib_root(root: Path) -> Path | None:
    project = root.parent / "mathlib-v4.34.0-reuse"
    src = project / ".lake" / "packages" / "mathlib"
    if (src / "Mathlib").is_dir():
        return src
    if (project / "Mathlib").is_dir():
        return project
    return None


def _markdown(report: dict, frozen: dict) -> str:
    h2 = report["h2"]
    lines = [
        "# Sprint 2 H2",
        "",
        f"Generated by `{report['generating_command']}`.",
        f"Mathlib revision: `{report['revision']}`.",
        f"Frozen pairs: {report['ground_truth_count']}.",
        f"sha256: `{report['ground_truth_sha256']}`.",
        "",
        "Do not edit this file by hand. Re-run the command.",
        "",
        "Aliases excluded: " + str(frozen["aliases_excluded"]) + ".",
        "Identical statements excluded: " + str(frozen["identical_statements_excluded"]) + ".",
        "No named replacement: " + str(frozen["no_replacement"]) + ".",
        "Replacement not resolved: " + str(frozen["unresolved"]) + ".",
        "",
        "Recall is the fraction of frozen pairs whose partner ranks at or above k",
        "against the old declaration. Unparsed signatures count as not recovered.",
        "",
        "| k | recovered | recall |",
        "|---:|---:|---:|",
    ]
    for k in (1, 5, 10, 50):
        recall = h2["recall"][str(k)]
        shown = "" if recall is None else f"{recall:.4f}"
        lines.append(f"| {k} | {h2['recovered'][k]} | {shown} |")
    lines += [
        "",
        f"Evaluated: {h2['evaluated']}. Unparsed: {h2['unparsed']}. Missing declaration: {h2['missing_declaration']}.",
        "",
        "## H3",
        "",
        report["h3"]["reason"],
        "",
        "## Duplicate list",
        "",
        report["duplicate_list"]["reason"],
        "",
    ]
    return "\n".join(lines)
