"""Write the Sprint 6 transport tables. No model calls."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

from consilean.ingest.corpus import ensure_checkout, load_spec, repo_root
from consilean.replay.cli import MATHLIB_REV, _mathlib_root
from consilean.transport.report import GENERATING_COMMAND, build, not_measured


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    root = repo_root()
    out = root / "docs" / "generated"
    out.mkdir(parents=True, exist_ok=True)
    mathlib = _mathlib_root(root)
    if mathlib is None:
        _write(out, not_measured("local Mathlib v4.34.0 tree not found"))
        return
    head = _head(mathlib)
    if head != MATHLIB_REV:
        _write(out, not_measured(f"local Mathlib is at {head}, pin is {MATHLIB_REV}"))
        return
    try:
        leanfrontier = ensure_checkout(
            load_spec(root / "corpora" / "leanfrontier.toml"),
            root / "corpora" / "cache" / "LeanFrontier",
        )
    except SystemExit as exc:
        _write(out, not_measured(str(exc)))
        return
    bridge = root / "lean" / "IsSquareModEq.lean"
    if not bridge.is_file():
        _write(out, not_measured("seed bridge lean/IsSquareModEq.lean is missing"))
        return
    prove = root.parent / "prove2me" / "missions"
    tauceti, tau_skips = _tau(root)
    report = build(
        mathlib=mathlib,
        leanfrontier=leanfrontier,
        bridge=bridge,
        prove2me=prove if prove.is_dir() else None,
        tauceti=tauceti,
        extra_skips=tau_skips,
        work=root / "corpora" / "cache" / "probes-sprint6",
        run_lean=True,
    )
    _write(out, report)
    print(f"wrote {out / 'sprint6-gaps.md'}")


def _tau(root: Path) -> tuple[Path | None, list[dict]]:
    spec_path = root / "corpora" / "tauceti.toml"
    if not spec_path.is_file():
        return None, [{"corpus": "Tau Ceti", "reason": "no pin at corpora/tauceti.toml"}]
    try:
        checkout = ensure_checkout(
            load_spec(spec_path),
            root / "corpora" / "cache" / "TauCeti",
            override_env=None,
        )
    except SystemExit as exc:
        return None, [{"corpus": "Tau Ceti", "reason": str(exc)}]
    return checkout, []


def _head(path: Path) -> str | None:
    result = subprocess.run(
        ["git", "-C", str(path), "rev-parse", "HEAD"],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return None
    return result.stdout.strip()


def _write(out: Path, report: dict) -> None:
    (out / "sprint6-gaps.json").write_text(json.dumps(_public(report), indent=2) + "\n", encoding="utf-8")
    (out / "sprint6-gaps.md").write_text(_gaps_md(report), encoding="utf-8")
    (out / "sprint6-controls.json").write_text(
        json.dumps({"generating_command": GENERATING_COMMAND, "config": report["config"], "controls": report["controls"]}, indent=2) + "\n",
        encoding="utf-8",
    )
    (out / "sprint6-controls.md").write_text(_controls_md(report), encoding="utf-8")
    (out / "sprint6-unportable.md").write_text(_unportable_md(report), encoding="utf-8")
    (out / "sprint6-rung2-targets.md").write_text(_rung2_md(report), encoding="utf-8")


def _public(report: dict) -> dict:
    """Drop fields the tables do not need. The match rows stay."""
    return {key: value for key, value in report.items() if key != "config"} | {"config": report["config"]}


def _gaps_md(report: dict) -> str:
    lines = [
        "# Sprint 6 gaps",
        "",
        f"Generated by `{report['generating_command']}`.",
        "",
        report["reason"] or "Measured once. The match rule is exact digest or normal form.",
        "",
        "## H4a",
        "",
    ]
    h4a = report.get("h4a") or {}
    lines += ["| corpus | matches | transported | fraction |", "|---|---:|---:|---:|"]
    for corpus, row in h4a.items():
        fraction = row["fraction"]
        shown = "" if fraction is None else f"{fraction:.4f}"
        lines.append(f"| {corpus} | {row['matches']} | {row['transported']} | {shown} |")
    lines += ["", "## Neighbourhood", "", "| declaration | gap | matches | rung 0 | rung 1 |", "|---|---|---:|---|---|"]
    for row in report["gaps"]:
        rung0 = (row.get("rung0") or {}).get("outcome", "")
        rung1 = (row.get("rung1") or {}).get("outcome", "")
        lines.append(
            f"| `{row['module']}.{row['name']}` | {row['gap']} | {len(row['matches'])} | {rung0} | {rung1} |"
        )
    lines += ["", "Rung 0 is an engineering check. A closure there is not a result.", ""]
    if any(row.get("engineering") for row in report["gaps"]):
        lines += ["## Engineering", ""]
        for row in report["gaps"]:
            if row.get("engineering"):
                lines.append(f"- `{row['name']}`: {row['engineering']}")
        lines.append("")
    lines += ["## Not measured", ""]
    for key, text in report["not_measured"].items():
        lines.append(f"- {key}: {text}")
    lines.append("")
    return "\n".join(lines)


def _controls_md(report: dict) -> str:
    controls = report["controls"]
    lines = [
        "# Sprint 6 controls",
        "",
        f"Generated by `{report['generating_command']}`.",
        "",
        f"Status: {controls['status']}.",
        "",
    ]
    if controls.get("reason"):
        lines += [controls["reason"], ""]
    if controls.get("note"):
        lines += [controls["note"], ""]
    recall = controls.get("recall") or {}
    lines += ["| k | recovered | recall |", "|---:|---:|---:|"]
    recovered = controls.get("recovered") or {}
    for k in (1, 5, 10):
        value = recall.get(str(k))
        shown = "" if value is None else f"{value:.4f}"
        lines.append(f"| {k} | {recovered.get(k, recovered.get(str(k), ''))} | {shown} |")
    lines.append("")
    return "\n".join(lines)


def _unportable_md(report: dict) -> str:
    lines = [
        "# Sprint 6 unportable",
        "",
        f"Generated by `{report['generating_command']}`.",
        "",
        "A statement that was not elaborated in the target toolchain.",
        "",
        "| declaration | corpus | reason |",
        "|---|---|---|",
    ]
    for row in report["unportable"]:
        lines.append(f"| `{row['module']}.{row['name']}` | {row['corpus']} | {row['reason']} |")
    lines.append("")
    return "\n".join(lines)


def _rung2_md(report: dict) -> str:
    lines = [
        "# Sprint 6 rung 2 targets",
        "",
        f"Generated by `{report['generating_command']}`.",
        "",
        "No model was called. A target is a gap whose rung 1 did not close.",
        "",
    ]
    if not report["rung2_targets"]:
        lines += ["No target.", ""]
    else:
        for row in report["rung2_targets"]:
            lines.append(f"- `{row['module']}.{row['name']}`")
        lines.append("")
    lines += [report["not_measured"]["rung2_calls"], ""]
    return "\n".join(lines)
