"""Assemble the Sprint 0 baseline report and write the generated tables."""

from __future__ import annotations

import json
import math
from pathlib import Path

from consilean.baselines.constants import drop_instance_constants, rank_constants
from consilean.baselines.text import distances_for, rank_text
from consilean.ingest.corpus import CorpusSpec
from consilean.ingest.declarations import load_declarations
from consilean.ingest.graph import directed_internal_edges, faithful_module_graph, undirected_distances
from consilean.ingest.observations import load_entrypoints
from consilean.vendor.import_graph import build, summarise

GENERATING_COMMAND = "uv run consilean-baseline"
TWIN_SHORT = {
    "isSquare_neg_one_mod_markovNumber",
    "exists_sq_modEq_neg_one_markovNumber",
}


def build_report(root: Path, spec: CorpusSpec) -> dict:
    """Faithful pilots plus the comment-stripping and instance-filter variants."""
    declarations = load_declarations(root, blank_block_comments=False)
    stripped = load_declarations(root, blank_block_comments=True)
    graph = faithful_module_graph(root)
    distances = distances_for(graph)
    text = rank_text(declarations, distances)
    text["modules"] = len(graph)
    text["directed_internal_import_edges"] = directed_internal_edges(graph)
    stripped_text = rank_text(stripped, distances)

    corrected_graph = build(root, spec.namespace)
    corrected_summary = summarise(corrected_graph, spec.namespace)
    corrected_summary["top_in_degree"] = [
        [module, degree] for module, degree in corrected_summary["top_in_degree"]
    ]
    corrected_distances = undirected_distances(corrected_graph)

    entrypoints = load_entrypoints(root)
    with_deps = {
        name: entry.type_dependencies
        for name, entry in entrypoints.items()
        if entry.type_dependencies
    }
    constants = rank_constants(with_deps)
    dropped = rank_constants(drop_instance_constants(with_deps))
    dropped["drop_instances"] = True

    return {
        "generating_command": GENERATING_COMMAND,
        "corpus": {
            "repo": spec.repo,
            "revision": spec.revision,
            "namespace": spec.namespace,
            "lean": spec.lean,
            "mathlib": spec.mathlib,
        },
        "faithful": {
            "text": text,
            "constants": constants,
        },
        "corrected": {
            "import_graph": corrected_summary,
            "text_strip_comments": {
                "public_declarations": stripped_text["public_declarations"],
                "pairs_above_cutoff": stripped_text["pairs_above_cutoff"],
                "twin": stripped_text["twin"],
            },
            "constants_drop_instances": {
                "entrypoints": dropped["entrypoints"],
                "pairs": dropped["pairs"],
                "twin": dropped["twin"],
                "top": dropped["top"],
            },
            "twin_module_distance": _twin_distance(declarations, distances, corrected_distances),
        },
    }


def write_generated(repo: Path, report: dict) -> tuple[Path, Path]:
    """Write the JSON and markdown tables under `docs/generated/`."""
    out = repo / "docs" / "generated"
    out.mkdir(parents=True, exist_ok=True)
    json_path = out / "leanfrontier-79800a5.json"
    md_path = out / "leanfrontier-79800a5.md"
    json_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    md_path.write_text(render_markdown(report), encoding="utf-8")
    return json_path, md_path


def render_markdown(report: dict) -> str:
    """Markdown tables. Every number here comes from `report`."""
    corpus = report["corpus"]
    text = report["faithful"]["text"]
    constants = report["faithful"]["constants"]
    corrected = report["corrected"]
    lines = [
        "# LeanFrontier baselines",
        "",
        f"Generated by `{report['generating_command']}`.",
        f"Repository: `{corpus['repo']}`",
        f"Revision: `{corpus['revision']}`",
        f"Toolchain: Lean `{corpus['lean']}`, Mathlib `{corpus['mathlib']}`.",
        "",
        "Do not edit this file by hand. Re-run the command.",
        "",
        "## Faithful text view",
        "",
        _bullet("public declarations", text["public_declarations"]),
        _bullet("modules", text["modules"]),
        _bullet("directed internal import edges", text["directed_internal_import_edges"]),
        _bullet("cross-module pairs above 0.25", text["pairs_above_cutoff"]),
        _twin_line("text", text["twin"]),
        "",
        "### Most similar pairs across modules",
        "",
        _text_table(text["top_similar"]),
        "",
        "### Most similar pairs with no import path",
        "",
        _text_table(text["top_no_import_path"]),
        "",
        "### Most similar pairs at import distance at least 4",
        "",
        _text_table(text["top_distance_at_least_4"]),
        "",
        "## Faithful constants view",
        "",
        _bullet("entrypoints with type dependencies", constants["entrypoints"]),
        _bullet("pairs", constants["pairs"]),
        _twin_line("constants", constants["twin"]),
        "",
        _constant_lists(constants["twin"]),
        "",
        "### Top pairs",
        "",
        _constants_table(constants["top"]),
        "",
        "## Corrected",
        "",
        "`import_graph.build` strips comments and accepts `public import` and `meta import`.",
        "The text variant tokenizes source after `strip_comments`, which also blanks `/--` docstrings.",
        "The constants variant drops constants whose last component starts with `inst`.",
        "That filter is a name heuristic, not an environment `isInstance` query.",
        "",
        "### Import graph",
        "",
        _bullet("modules", corrected["import_graph"]["modules"]),
        _bullet("internal edges", corrected["import_graph"]["internal_edges"]),
        _bullet("external edges", corrected["import_graph"]["external_edges"]),
        "",
        "### Text view after strip_comments",
        "",
        _bullet("public declarations", corrected["text_strip_comments"]["public_declarations"]),
        _bullet("cross-module pairs above 0.25", corrected["text_strip_comments"]["pairs_above_cutoff"]),
        _twin_line("text", corrected["text_strip_comments"]["twin"]),
        "",
        "### Constants view with instance names dropped",
        "",
        _bullet("entrypoints kept", corrected["constants_drop_instances"]["entrypoints"]),
        _bullet("pairs", corrected["constants_drop_instances"]["pairs"]),
        _twin_line("constants", corrected["constants_drop_instances"]["twin"]),
        "",
        "### Top pairs after dropping instance names",
        "",
        _constants_table(corrected["constants_drop_instances"]["top"]),
        "",
        "### Distance between the twin's modules",
        "",
        _bullet("faithful", _fmt_distance(corrected["twin_module_distance"]["faithful"])),
        _bullet("corrected", _fmt_distance(corrected["twin_module_distance"]["corrected"])),
        "",
    ]
    return "\n".join(lines)


def print_report(report: dict) -> None:
    """Print the locked lines and the corrected twin lines."""
    text = report["faithful"]["text"]
    constants = report["faithful"]["constants"]
    corrected = report["corrected"]
    print(
        f"{text['public_declarations']} public declarations in {text['modules']} modules; "
        f"{text['directed_internal_import_edges']} directed internal import edges"
    )
    _print_twin("Known duplicate (the sqrt(-1) twin), text", text["twin"])
    print(
        f"{constants['entrypoints']} entrypoints with recorded type dependencies; "
        f"{constants['pairs']} pairs"
    )
    _print_twin("sqrt(-1) twin under the constants view", constants["twin"])
    if constants["twin"]:
        print("  shared constants:", constants["twin"]["shared_constants"])
    print(
        "strip_comments text view: "
        f"{corrected['text_strip_comments']['public_declarations']} declarations, "
        f"{corrected['text_strip_comments']['pairs_above_cutoff']} pairs above 0.25"
    )
    _print_twin("sqrt(-1) twin under strip_comments", corrected["text_strip_comments"]["twin"])
    graph = corrected["import_graph"]
    print(
        f"corrected import graph: {graph['modules']} modules, "
        f"{graph['internal_edges']} internal edges, {graph['external_edges']} external edges"
    )
    dropped = corrected["constants_drop_instances"]
    print(f"constants view with inst-names dropped: {dropped['entrypoints']} entrypoints, {dropped['pairs']} pairs")
    _print_twin("sqrt(-1) twin with inst-names dropped", dropped["twin"])


def _twin_distance(declarations, faithful, corrected) -> dict:
    modules = [decl.module for decl in declarations if decl.name in TWIN_SHORT]
    if len(modules) != 2:
        return {"faithful": None, "corrected": None, "modules": modules}
    left, right = modules
    return {
        "modules": [left, right],
        "faithful": _lookup(faithful, left, right),
        "corrected": _lookup(corrected, left, right),
    }


def _lookup(distances: dict[str, dict[str, int]], left: str, right: str) -> int | None:
    if left not in distances:
        return None
    distance = distances[left].get(right, math.inf)
    if math.isinf(distance):
        return None
    return distance


def _pair_row_distance(distance: int | None) -> str:
    return "∞" if distance is None else str(distance)


def _fmt_distance(distance: int | None) -> str:
    return "none" if distance is None else str(distance)


def _bullet(label: str, value: object) -> str:
    return f"- {label}: {value}"


def _twin_line(kind: str, twin: dict | None) -> str:
    if not twin:
        return f"- sqrt(-1) twin ({kind}): not in the ranked pairs"
    distance = ""
    if "distance" in twin:
        distance = f", distance {_pair_row_distance(twin['distance'])}"
    return (
        f"- sqrt(-1) twin ({kind}): score {twin['score']:.2f}, "
        f"rank {twin['rank']} of {twin['of']}{distance}"
    )


def _print_twin(label: str, twin: dict | None) -> None:
    if not twin:
        print(f"{label}: not in the ranked pairs")
        return
    extra = ""
    if "distance" in twin:
        extra = f", distance {_pair_row_distance(twin['distance'])}"
    print(f"{label}: score {twin['score']:.2f}, rank {twin['rank']} of {twin['of']}{extra}")


def _constant_lists(twin: dict | None) -> str:
    if not twin:
        return ""
    return "\n".join(
        [
            "Shared constants:",
            "",
            _code_list(twin["shared_constants"]),
            "",
            "Only in the IsSquare form:",
            "",
            _code_list(twin["only_is_square"]),
            "",
            "Only in the ModEq form:",
            "",
            _code_list(twin["only_mod_eq"]),
        ]
    )


def _code_list(items: list[str]) -> str:
    if not items:
        return "(none)"
    return "\n".join(f"- `{item}`" for item in items)


def _text_table(rows: list[dict]) -> str:
    header = "| score | distance | left | right |"
    rule = "|---:|---:|---|---|"
    body = [
        f"| {row['score']:.2f} | {_pair_row_distance(row['distance'])} | `{_short(row['left'])}` | `{_short(row['right'])}` |"
        for row in rows
    ]
    return "\n".join([header, rule, *body]) if body else "(none)"


def _constants_table(rows: list[dict]) -> str:
    header = "| score | left | right |"
    rule = "|---:|---|---|"
    body = [
        f"| {row['score']:.2f} | `{_short(row['left'])}` | `{_short(row['right'])}` |"
        for row in rows
    ]
    return "\n".join([header, rule, *body]) if body else "(none)"


def _short(name: str) -> str:
    return name.removeprefix("LeanFrontier.")
