"""List Sprint 3 targets. Do not call a model while the budget is closed."""

from __future__ import annotations

import argparse
import json

from consilean.agents.budget import load_budget
from consilean.agents.log import append_attempt
from consilean.agents.targets import ATTEMPT_ORDER, FIRST_TARGETS
from consilean.ingest.corpus import repo_root

GENERATING_COMMAND = "uv run consilean-sprint3"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    root = repo_root()
    budget = load_budget(root / "corpora" / "sprint3-budget.toml")
    out = root / "docs" / "generated"
    out.mkdir(parents=True, exist_ok=True)
    log_path = out / "sprint3-attempts.jsonl"
    record = {
        "attempts": list(ATTEMPT_ORDER),
        "model": None,
        "outcome": "not_called",
        "per_pair_tokens": budget.per_pair_tokens,
        "prompt_hash": None,
        "reason": _reason(budget.is_open),
        "targets": [label for label, _left, _right in FIRST_TARGETS],
        "tokens": 0,
        "total_tokens": budget.total_tokens,
    }
    if budget.is_open:
        record["reason"] = "Budget is set, but no assistant is configured. No call was made."
    append_attempt(log_path, record)
    report = {
        "budget_open": budget.is_open,
        "generating_command": GENERATING_COMMAND,
        "per_pair_tokens": budget.per_pair_tokens,
        "targets": [
            {"label": label, "left": left, "right": right} for label, left, right in FIRST_TARGETS
        ],
        "total_tokens": budget.total_tokens,
    }
    (out / "sprint3-targets.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    (out / "sprint3-targets.md").write_text(_markdown(report, record["reason"]), encoding="utf-8")
    print(record["reason"])
    print(f"wrote {out / 'sprint3-targets.md'}")


def _reason(open_budget: bool) -> str:
    if open_budget:
        return "Budget is set, but no assistant is configured. No call was made."
    return "Budget is closed. Set per_pair_tokens and total_tokens above zero before any model call."


def _markdown(report: dict, reason: str) -> str:
    lines = [
        "# Sprint 3 targets",
        "",
        f"Generated by `{report['generating_command']}`.",
        "",
        reason,
        "",
        "Do not edit this file by hand. Re-run the command.",
        "",
        "| label | left | right |",
        "|---|---|---|",
    ]
    for target in report["targets"]:
        lines.append(f"| {target['label']} | `{target['left']}` | `{target['right']}` |")
    lines.append("")
    return "\n".join(lines)
