"""Probe the Sprint 1 far-near lists and the section 5 controls."""

from __future__ import annotations

import argparse
import json
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from consilean.ingest.corpus import ensure_checkout, load_spec, repo_root
from consilean.ingest.declarations import load_declarations
from consilean.probes.lists import probe_jobs
from consilean.probes.runner import build_cache, link_mathlib_packages, probe_job

GENERATING_COMMAND = "uv run consilean-probes"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    root = repo_root()
    spec = load_spec(root / "corpora" / "leanfrontier.toml")
    cache = ensure_checkout(spec, root / "corpora" / "cache" / "LeanFrontier")
    mathlib = root.parent / "mathlib-v4.34.0-reuse"
    if mathlib.is_dir():
        link_mathlib_packages(cache, mathlib)
    build = build_cache(cache)
    declarations = [decl for decl in load_declarations(cache) if decl.kind in {"theorem", "lemma"}]
    markdown = (root / "docs" / "generated" / "sprint1-leanfrontier-79800a5.md").read_text(encoding="utf-8")
    jobs = probe_jobs(cache, declarations, markdown)
    report: dict = {
        "generating_command": GENERATING_COMMAND,
        "revision": spec.revision,
        "timeout_seconds": 10,
        "tactics": ["rfl", "simp", "norm_num", "tauto", "omega", "decide", "exact?", "apply?", "aesop", "grind"],
        "build_returncode": build.returncode,
    }
    if build.returncode != 0:
        tail = (build.stderr or build.stdout).strip().splitlines()
        report["build_error"] = tail[-1][:400] if tail else "lake build failed"
        report["pairs"] = []
    else:
        work = root / "corpora" / "cache" / "probes"

        def run(job: dict) -> dict:
            print(f"probe {job['left_name']} {job['right_name']}", flush=True)
            return probe_job(cache, job, work)

        with ThreadPoolExecutor(max_workers=3) as pool:
            report["pairs"] = list(pool.map(run, jobs))
    out = root / "docs" / "generated"
    out.mkdir(parents=True, exist_ok=True)
    json_path = out / "sprint1-probes.json"
    md_path = out / "sprint1-probes.md"
    json_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    md_path.write_text(_markdown(report), encoding="utf-8")
    print(f"pairs {len(report['pairs'])}")
    print(f"wrote {json_path}")
    print(f"wrote {md_path}")


def _markdown(report: dict) -> str:
    lines = [
        "# Sprint 1 probes",
        "",
        f"Generated by `{report['generating_command']}`.",
        f"Revision: `{report['revision']}`.",
        f"Timeout: {report['timeout_seconds']} seconds per tactic.",
        "",
        "Do not edit this file by hand. Re-run the command.",
        "",
    ]
    if report["build_returncode"] != 0:
        lines.append(f"Build failed: `{report.get('build_error', '')}`")
        lines.append("")
        return "\n".join(lines)
    lines += [
        "| list | left | right | iff | left to right | right to left |",
        "|---|---|---|---|---|---|",
    ]
    for pair in report["pairs"]:
        by_dir = {item["direction"]: item for item in pair["directions"]}
        lines.append(
            "| {list} | `{left}` | `{right}` | {iff} | {ltr} | {rtl} |".format(
                list=pair["list"],
                left=_short(pair["left"]),
                right=_short(pair["right"]),
                iff=_cell(by_dir["iff"]),
                ltr=_cell(by_dir["left_to_right"]),
                rtl=_cell(by_dir["right_to_left"]),
            )
        )
    lines.append("")
    return "\n".join(lines)


def _short(name: str) -> str:
    return name.removeprefix("LeanFrontier.")


def _cell(item: dict) -> str:
    if item["outcome"] == "closed":
        return f"closed ({item['tactic']})"
    return item["outcome"]
