"""Probe the pairs the first H2 run recovered at k = 10.

The names are the ones that ranked inside k = 10 before the later parser
change. A direction that closes is the only reason to add a duplicate-list row.
"""

from __future__ import annotations

import json
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from consilean.ingest.corpus import repo_root
from consilean.probes.runner import probe_job

# Full names from the first H2 ranking, not recomputed after the parser change.
RECOVERED = (
    ("Mathlib.Algebra.MvPolynomial.Equiv.sumToIter_C", "Mathlib.Algebra.MvPolynomial.Equiv.sumRingEquiv_C"),
    (
        "Mathlib.Algebra.Order.Ring.Unbundled.Basic.two_mul_le_add_of_sq_eq_mul",
        "Mathlib.Algebra.Order.Ring.Unbundled.Basic.two_mul_le_add_of_sq_le_mul",
    ),
    ("Mathlib.Analysis.Normed.Lp.PiLp.dist_toLp_single_same", "Mathlib.Analysis.Normed.Lp.PiLp.dist_single_same"),
    ("Mathlib.Analysis.Normed.Lp.PiLp.edist_toLp_single_same", "Mathlib.Analysis.Normed.Lp.PiLp.edist_single_same"),
    ("Mathlib.Analysis.Normed.Lp.PiLp.nndist_toLp_single_same", "Mathlib.Analysis.Normed.Lp.PiLp.nndist_single_same"),
    (
        "Mathlib.LinearAlgebra.AffineSpace.Combination.affineCombination_affineCombinationSingleWeights",
        "Mathlib.LinearAlgebra.AffineSpace.Combination.affineCombination_piSingle",
    ),
    (
        "Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional.finite_of_fin_dim_affineIndependent",
        "Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional.finiteDimensional_iff_finite",
    ),
    (
        "Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional.finite_set_of_fin_dim_affineIndependent",
        "Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional.finiteDimensional_iff_setFinite",
    ),
    (
        "Mathlib.NumberTheory.ModularForms.LevelOne.DimensionFormula.divDiscriminant_apply",
        "Mathlib.NumberTheory.ModularForms.LevelOne.DimensionFormula.discriminantEquiv_apply",
    ),
    ("Mathlib.NumberTheory.NumberField.House.house_pow_le", "Mathlib.NumberTheory.NumberField.House.house_pow"),
    (
        "Mathlib.Probability.Distributions.Poisson.Basic.poissonPMF",
        "Mathlib.Probability.Distributions.Poisson.Basic.poissonMeasure",
    ),
    (
        "Mathlib.SetTheory.Ordinal.Exponential.omega0_opow_mul_nat_lt",
        "Mathlib.SetTheory.Ordinal.Exponential.opow_mul_lt_opow",
    ),
    ("Mathlib.SetTheory.Ordinal.Topology.IsAcc", "Mathlib.Topology.Defs.Filter.AccPt"),
)


def mathlib_project(root: Path) -> Path:
    src = root.parent / "mathlib-v4.34.0-reuse" / ".lake" / "packages" / "mathlib"
    if (src / "lakefile.lean").is_file() or (src / "lakefile.toml").is_file():
        return src
    project = root.parent / "mathlib-v4.34.0-reuse"
    if (project / "lakefile.lean").is_file() or (project / "lakefile.toml").is_file():
        return project
    raise SystemExit("local Mathlib v4.34.0 lake project not found")


def jobs_from_freeze(frozen: dict) -> list[dict]:
    by_pair = {(pair["old"], pair["new"]): pair for pair in frozen["pairs"]}
    jobs = []
    for old, new in RECOVERED:
        pair = by_pair.get((old, new))
        if pair is None:
            raise SystemExit(f"frozen set has no pair {old} → {new}")
        old_module, _, old_name = old.rpartition(".")
        new_module, _, new_name = new.rpartition(".")
        jobs.append(
            {
                "list": "h2-recovered-k10",
                "left_module": old_module,
                "left_name": old_name,
                "left_sig": pair["old_statement"],
                "right_module": new_module,
                "right_name": new_name,
                "right_sig": pair["new_statement"],
            }
        )
    return jobs


def write_duplicates(path: Path, results: list[dict], command: str) -> int:
    closed = [
        item
        for item in results
        if any(direction["outcome"] == "closed" for direction in item["directions"])
    ]
    lines = [
        "# Probable duplicates",
        "",
        f"Generated by `{command}`.",
        "",
    ]
    if not closed:
        lines += [
            "No row is listed. The checker did not close an equivalence in this run.",
            "",
        ]
    else:
        lines += [
            "A row is listed only when a preregistered tactic closed one direction.",
            "",
            "| old | new | direction | tactic |",
            "|---|---|---|---|",
        ]
        for item in closed:
            for direction in item["directions"]:
                if direction["outcome"] != "closed":
                    continue
                lines.append(
                    f"| `{item['left']}` | `{item['right']}` | {direction['direction']} | `{direction['tactic']}` |"
                )
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
    return len(closed)


def main() -> None:
    root = repo_root()
    frozen = json.loads((root / "docs" / "generated" / "sprint2-ground-truth.json").read_text(encoding="utf-8"))
    project = mathlib_project(root)
    work = root / "corpora" / "cache" / "probes-h2"
    jobs = jobs_from_freeze(frozen)
    results = []
    with ThreadPoolExecutor(max_workers=3) as pool:
        for result in pool.map(lambda job: probe_job(project, job, work), jobs):
            results.append(result)
            outcomes = ", ".join(f"{d['direction']}={d['outcome']}" for d in result["directions"])
            print(f"{result['left']}  {outcomes}", flush=True)
    out = root / "docs" / "generated"
    command = "uv run consilean-h2-probes"
    (out / "sprint2-recovered-probes.json").write_text(
        json.dumps({"generating_command": command, "results": results}, indent=2) + "\n",
        encoding="utf-8",
    )
    closed_rows = [
        item
        for item in results
        if any(direction["outcome"] == "closed" for direction in item["directions"])
    ]
    if closed_rows:
        write_duplicates(out / "sprint2-duplicates.md", results, command)
    print(f"closed {len(closed_rows)} of {len(results)}")


if __name__ == "__main__":
    main()
